# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoLimitsListWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.limitsChoicesLabel = QtWidgets.QLabel(Dialog)
        self.limitsChoicesLabel.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.limitsChoicesLabel.setObjectName("limitsChoicesLabel")
        self.limitsChosenLabel = QtWidgets.QLabel(Dialog)
        self.limitsChosenLabel.setGeometry(QtCore.QRect(10, 230, 371, 20))
        self.limitsChosenLabel.setText("")
        self.limitsChosenLabel.setObjectName("limitsChosenLabel")
        self.listWidgetLimits = QtWidgets.QListWidget(Dialog)
        self.listWidgetLimits.setGeometry(QtCore.QRect(130, 30, 256, 192))
        self.listWidgetLimits.setObjectName("listWidgetLimits")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.limitsChoicesLabel.setText(_translate("Dialog", "Choose Limits:"))
